name: Build Extension ZIP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip the extension
      run: zip -r linkedin-ExTRACTOR.zip . -x "*.git*" "*.github*" "node_modules/*" "README.md"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linkedin-extractor-zip
        path: linkedin-extractor.zip
